<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sbd</string>
	</array>
	<key>name</key>
	<string>latex-songs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\\\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.tsx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.tsx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.definition.chord.latex-songs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\^</string>
			<key>name</key>
			<string>string.repetition.chord.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(begin|end)song</string>
			<key>name</key>
			<string>keyword.control.song.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(begin|end)scripture</string>
			<key>name</key>
			<string>keyword.control.less.scripture.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(begin|end)verse</string>
			<key>name</key>
			<string>keyword.control.less.verse.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(begin|end)chorus</string>
			<key>name</key>
			<string>keyword.control.less.chorus.latex-songs</string>
		</dict>
		<!-- Commands -->
		<dict>
			<key>match</key>
			<string>\\indexentry</string>
			<key>name</key>
			<string>keyword.operator.new.indexentry.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\indextitleentry</string>
			<key>name</key>
			<string>keyword.operator.new.indextitleentry.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\setlicense</string>
			<key>name</key>
			<string>keyword.operator.new.setlicense.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\meter</string>
			<key>name</key>
			<string>keyword.operator.new.meter.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\capo</string>
			<key>name</key>
			<string>keyword.operator.new.capo.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\transpose</string>
			<key>name</key>
			<string>keyword.operator.new.transpose.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\chords(on|off)</string>
			<key>name</key>
			<string>keyword.operator.new.chords.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\measures</string>
			<key>name</key>
			<string>keyword.operator.new.measures.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\norepchoruses</string>
			<key>name</key>
			<string>keyword.operator.new.norepchoruses.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\repchoruses</string>
			<key>name</key>
			<string>keyword.operator.new.repchoruses.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\musicnote{[^{}]*}</string>
			<key>name</key>
			<string>keyword.operator.new.musicnote.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\textnote{[^{}]*}</string>
			<key>name</key>
			<string>keyword.operator.new.textnote.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\meter{\d\+}{\d\+}</string>
			<key>name</key>
			<string>keyword.operator.new.meter.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\brk</string>
			<key>name</key>
			<string>keyword.operator.new.brk.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\memorize</string>
			<key>name</key>
			<string>keyword.operator.new.memorize.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\replay</string>
			<key>name</key>
			<string>keyword.operator.new.replay.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\rep{[^{}]*}</string>
			<key>name</key>
			<string>keyword.operator.new.rep.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(l|r)rep</string>
			<key>name</key>
			<string>keyword.operator.new.lrrep.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\nolyrics</string>
			<key>name</key>
			<string>keyword.operator.new.nolyrics.latex-songs</string>
		</dict>
		<!-- Fix LaTeX -->
		<dict>
			<key>match</key>
			<string>''</string>
			<key>name</key>
			<string>keyword.control.less.chorus.begin.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>``</string>
			<key>name</key>
			<string>keyword.control.less.chorus.begin.latex-songs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'</string>
			<key>name</key>
			<string>text</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`</string>
			<key>name</key>
			<string>text</string>
		</dict>
		<!-- Include LaTeX -->
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex.songs</string>
	<key>uuid</key>
	<string>8C70CDF8-3C7A-47EC-8999-2588DCC876B1</string>
</dict>
</plist>
